### PR TITLE
feat: :art: format phone number

### PR DESCRIPTION
**Pull request by pdt1806**
@tobycm refactor if @tobycm want to

### CODE REVIEW

**Comment by tobycm** [comment]
conflict 😬 
@pdt1806 solve pls xddd

**Comment by pdt1806** [comment]
oh damn ok

**Comment by pdt1806** [comment]
@tobycm resolved

**Review by tobycm — APPROVED** [review]
Naisu

**Comment by pdt1806** [comment]
enjoy ur meal

**Pull request merged**
