### PR TITLE
refactor: :sparkles: new style for menu title

### PR DESCRIPTION
**Pull request by pdt1806**
so i think that the color of the titles are better (it stays blue all the time)
and it's now a menu item, so when hovering on it brings users a feeling that the title is clickable

if @tobycm doesn't like the menu title, feel free to adjust

### CODE REVIEW

**Comment by tobycm** [comment]
Screenshots pls 🙏

**Comment by pdt1806** [comment]
bruh @tobycm 

image

**Comment by tobycm** [comment]
Beautiful, approved

**Comment by pdt1806** [comment]
approve in review then merge pls @tobycm

**Comment by tobycm** [comment]
On phone can't. Just merge
Take my comment as approval lol

**Comment by pdt1806** [comment]
ok

**Pull request merged**
