### PR TITLE
feat: :sparkles: better ux for user if they can't find the X lol

### PR DESCRIPTION
**Pull request by tobycm**

### CODE REVIEW

**Review by pdt1806 — CHANGES_REQUESTED** [review]
couldn't tell there is a button down there if all categories are expanded

**Comment by pdt1806** [comment]
@tobycm updated but i personally don't think it is necessary

1. they can find the X, it's clear enough; not to mention they can press the overlay (common sense)
2. filters are made when checking the boxes, so an 'apply' button seems weird

i'll let you decide

**Comment by tobycm** [comment]
> couldn't tell there is a button down there if all categories are expanded

doesn't need to, it's only for ppl who expects one down there

**Comment by pdt1806** [comment]
> > couldn't tell there is a button down there if all categories are expanded
> 
> doesn't need to, it's only for ppl who expects one down there

scrolling 12000px just to find 1 button is not what a user would expect

**Review by pdt1806 — COMMENTED** [review]
siu

**Comment by tobycm** [comment]
> > > couldn't tell there is a button down there if all categories are expanded
> > 
> > 
> > doesn't need to, it's only for ppl who expects one down there
> 
> scrolling 12000px just to find 1 button is not what a user would expect

ik at least 1 person that expects it sooooooo why not

**Pull request merged**
