### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by tobycm**
still not enough, needs to do order of loading i guess

### CODE REVIEW

**Review by pdt1806 — CHANGES_REQUESTED** [review]
### Issues:
- Thumb images are used to serve in Gallery even when zooming in.
- Some thumb images in Gallery are too small and pixelated.

### Notes:
- Most of the thumb images are blurry on large display/monitor.
- A mix of thumb images and [non-thumb .webp images](https://github.com/pocketbase/pocketbase/issues/825) in Catalog is not cool.

**Comment by tobycm** [comment]
hey I added fetchpriority so i think it is better to use original images now. please rereview

**Comment by tobycm** [comment]
ok nvm that i readded thumb but higher res now

**Review by pdt1806 — APPROVED** [review]
it works for sure

**Pull request merged**
